name: Production Deployment
run-name: ${{ github.workflow }} run by ${{ github.actor }}
on:
  push:
    branches:
      - master
jobs:
  restart-docker-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository code
        uses: actions/checkout@v4

      - name: Pull the latest code and copy it over the html directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: sudo ./util/scripts/update_nekonya_docs.sh